### PR TITLE
fix(*): cannot import module with single path

### PR DESCRIPTION
**Pull request by JulienGrv**

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Thanks for the PR. But this is not a valid change &ndash; it actually breaks its current (correct) behaviour.

**Comment by JulienGrv** [comment]
Ah okay I see now, sorry I made this fix in a hurry this morning for my own usage. I will fix that this afternoon

**Comment by JulienGrv** [comment]
I don't understand the need for this parent_dir argument. Why can't I use a relative path to my module?

**Comment by NiklasRosenstein** [comment]
As the name suggests, the `parent_dir` argument allows you to specify a different parent directory for relative paths passed to the `path` argument. If the `parent_dir` argument is not passed, it will fall back to the parent directory of the file that you call the `localimport()` constructor from.

**Comment by JulienGrv** [comment]
Ok I understand now! Thank you for your quick response! and congrats for the module, it is very useful!

**Pull request closed without merging**
